platform: linux

image_resource:
  type: registry-image
  source: { repository: busybox }

inputs:
- name: silly-repo

outputs:
- name: deployment-stuff

params:
  APP_NAME:

run:
  path: silly-repo/ci/tasks/build-manifest.sh