
platform: linux
image_resource:
  type: registry-image
  source: { repository: busybox }

outputs:
- name: deployment-stuff
params:
  APP_NAME:
run:
  path: sh
  args:
  - -exc
  - |
    cat <<EOF > deployment-stuff/manifest.yml
    ---
    applications:
      - name: $APP_NAME
        memory: 64M
    EOF
